insert into location (street, street_nr, city, country) VALUES ('Poggibonsi', 2, 'Toscana', 'Italy');
insert into location (street, street_nr, city, country) VALUES ('Nisaki', 6, 'Nisaki', 'Greece');
insert into location (street, street_nr, city, country) VALUES ('Høylandet', 6, 'Trøndelag', 'Norway');
insert into location (street, street_nr, city, country) VALUES ('Bistrita-Bargaului', 9, 'Județul Bistrița-Năsăud', 'România');
insert into location (street, street_nr, city, country) VALUES ('Square', 83, 'New York', 'USA');
insert into location (street, street_nr, city, country) VALUES ('Greater London', 83, 'England', 'United Kingdom');
insert into location (street, street_nr, city, country) VALUES ('Greater London', 85, 'England', 'United Kingdom');
insert into location (street, street_nr, city, country) VALUES ('Marrakech', 85, 'Marrakech-Safi', 'Maroc');
insert into location (street, street_nr, city, country) VALUES ('Sidemen', 85, 'Bali', 'Indonesia');
insert into location (street, street_nr, city, country) VALUES ('Osa', 85, 'Puntaneras', 'Costa Rica');
